[package]
name = "sparticles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-winit = { git = "https://github.com/Norlock/egui.git"}
egui-wgpu = { git = "https://github.com/Norlock/egui.git"}
glam = "0.24.2"
pollster = "0.3.0"
image = { version = "0.24.7", features = ["png", "jpeg"] }
env_logger = "0.10.0"
bytemuck = "1.14.0"
rand = "0.8.5"
encase = "0.6.1"
serde_json = "1.0.107"
serde = { version = "1.0.189", features = ["derive"] }

