[package]
name = "sparticles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
glam = { version = "0.24.2", features = ["serde"] }
pollster = "0.3.0"
image = { version = "0.24.7", features = ["png", "jpeg"] }
env_logger = "0.10.0"
bytemuck = "1.14.0"
rand = "0.8.5"
encase = { version = "0.6.1", features = ["glam"] }
serde_json = "1.0.107"
serde = { version = "1.0.189", features = ["derive"] }
egui-winit = { git = "https://github.com/norlock/egui.git", branch = "collapsing-header-events" }
egui-wgpu = { git = "https://github.com/norlock/egui.git", branch = "collapsing-header-events" }
wgpu-profiler = { version = "0.15.0" }
gltf = { version = "1.3.0", features = ["KHR_materials_ior", "KHR_materials_specular", "KHR_materials_pbrSpecularGlossiness", "KHR_materials_transmission", "KHR_materials_emissive_strength", "KHR_texture_transform", "KHR_materials_variants", "KHR_materials_volume", "KHR_lights_punctual", "KHR_materials_unlit"] }
anyhow = "1.0.75"
