[package]
name = "sparticles-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
egui_wgpu_backend = "0.25"
egui_winit_platform = "0.19.0"
epi = "0.17.0"
glam = "0.24.1"
pollster = "0.3.0"
image = { version = "0.24.6", features = ["png", "jpeg"] }
winit = { version = "0.28.6", features = ["wayland"] }
env_logger = "0.10.0"
bytemuck = "1.13.1"
