[package]
name = "sparticles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-winit = "0.22.0"
egui-wgpu = "0.22.0"
glam = "0.24.1"
pollster = "0.3.0"
image = { version = "0.24.6", features = ["png", "jpeg"] }
env_logger = "0.10.0"
bytemuck = "1.13.1"
rand = "0.8.5"
encase = "0.6.1"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
