[package]
name = "sparticles_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sparticles_app = { path = "../sparticles_app" }

[lib]
name = "sparticles_editor"
path = "src/lib.rs"
